#!/bin/sh

mkdir -p api

echo \
    "/*\n" \
    "* This file is autogenerated by $0\n" \
    "* Do not change\n" \
    "*/" \
    > api/typhon.h

# Cut out everything within the _TYPH_Internal namespace from the public header
start_internal_pattern='^namespace _TYPH_Internal {$'
end_internal_pattern='^} \/\/ namespace _TYPH_Internal$'
sed_string="/${start_internal_pattern}/,/${end_internal_pattern}/d"

sed "${sed_string}" include/types.h >> api/typhon.h
sed "${sed_string}" include/utilities.h >> api/typhon.h
sed "${sed_string}" include/core.h >> api/typhon.h
sed "${sed_string}" include/register.h >> api/typhon.h
sed "${sed_string}" include/decomposition.h >> api/typhon.h
sed "${sed_string}" include/exchange.h >> api/typhon.h
sed "${sed_string}" include/quantity.h >> api/typhon.h
sed "${sed_string}" include/keys.h >> api/typhon.h
sed "${sed_string}" include/collect.h >> api/typhon.h
sed "${sed_string}" include/dt_reduce.h >> api/typhon.h
sed "${sed_string}" include/distribute.h >> api/typhon.h
sed "${sed_string}" include/serialise.h >> api/typhon.h
